In [1]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import tensorflow as tf

# 수술 환자 데이터 불러오기
# 종량의 유형, 폐활량, 호흡 곤란여부, 고통 정도, 기침, 천식 여부, 수술 후 생존 여부 예측하기
Data_set = np.loadtxt('../data/ThoraricSurgery.csv',delimiter=",")
# 환자의 기록과 수술 결과를 X와 Y로 구분
X = Data_set[:,0:17]
Y = Data_set[:,17]
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [2]:
X

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [3]:
Y

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0.

In [4]:
print(len(X[0]))

17


In [5]:
# 딥러닝 구조
model = Sequential()
model.add(Dense(30, input_dim=17,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [6]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=100,batch_size=10)

Epoch 1/100
47/47 [==============================] - 0s 1ms/step - loss: 12.0419 - accuracy: 0.4149
Epoch 2/100
47/47 [==============================] - 0s 1ms/step - loss: 1.0146 - accuracy: 0.8404
Epoch 3/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4936 - accuracy: 0.8426
Epoch 4/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4644 - accuracy: 0.8468
Epoch 5/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4731 - accuracy: 0.8447
Epoch 6/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4560 - accuracy: 0.8426
Epoch 7/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4632 - accuracy: 0.8447
Epoch 8/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4590 - accuracy: 0.8468
Epoch 9/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4656 - accuracy: 0.8426
Epoch 10/100
47/47 [==============================] - 0s 1ms/step - loss: 0.4738 - accuracy: 0.8426
Epoch 11

In [7]:
print('\n Accuracy: %.4f' % (model.evaluate(X,Y)[1]))

15/15 [==============================] - 0s 858us/step - loss: 0.3773 - accuracy: 0.8532

 Accuracy: 0.8532
